import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloProvider } from "@apollo/client";
import apolloClient from "@/app/login/aplloClient.js"; // Adjust the path accordingly

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ApolloProvider client={apolloClient}>
        <body className={inter.className}>{children}</body>
      </ApolloProvider>
    </html>
  );
}
